

// Business registration 1
POST https://business-startup-api.herokuapp.com/api/registerBusiness
Content-Type: application/json

{
    "firstName" : "Tyler",
    "lastName": "Tyler",
    "email": "tyler@email.com",
    "phoneNumber": "123456789",
    "password": "123456"

}
###